# Site settings
title: JBlog
email: jasonmaa3955@gmail.com
description: My personal blog about me.
baseurl: ""
url: ""

author:
  name     : 'Jason Maa'
  

github: https://github.com/treechicken
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

gems: [jekyll-paginate]
