# Site settings
title: JBlog
email: jasonmaa3955@gmail.com
description: Personal Blog
baseurl: ""
url: ""

author:
  name     : 'Jason Maa'


github: https://github.com/jasmaa

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

gems: [jekyll-paginate]
